port: /dev/ydlidar
baudrate: 115200
frame_id: base_scan
low_exposure: false
resolution_fixed: true
auto_reconnect: true
reversion: false
angle_min: -180
angle_max: 180
range_min: 0.1
range_max: 16.0
samp_rate: 9
frequency: 7
